
  heroes-db:
    image: postgres:14
    container_name: heroes-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ../../../rest-heroes/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql
