version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    labels:
      - "version-upgrade"

  # npm dependencies
  - package-ecosystem: npm
    directory: ui-super-heroes/src/main/webui
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: main
    labels:
      - "version-upgrade"
      - ui

  # Dependencies for the 3.15.Final branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: 3.15.Final
    labels:
      - "version-upgrade"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      - dependency-name: "io.quarkus.platform:quarkus-bom"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.quarkus.platform:quarkus-maven-plugin"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.github.microcks.quarkus:quarkus-microcks"
      - dependency-name: "io.quarkiverse.langchain4j:quarkus-langchain4j-bom"
      - dependency-name: "org.wiremock:wiremock-grpc-extension"

  # Dependencies for the rhbq-3.15 branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-3.15
    labels:
      - "version-upgrade"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      - dependency-name: "com.redhat.quarkus.platform:quarkus-bom"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "com.redhat.quarkus.platform:quarkus-maven-plugin"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.github.microcks.quarkus:quarkus-microcks"
      - dependency-name: "io.quarkiverse.langchain4j:quarkus-langchain4j-bom"
      - dependency-name: "org.wiremock:wiremock-grpc-extension"

  # Dependencies for the 3.8.Final branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: 3.8.Final
    labels:
      - "version-upgrade"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      - dependency-name: "io.quarkus.platform:quarkus-bom"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.quarkus.platform:quarkus-maven-plugin"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.quarkus:quarkus-panache-common"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.github.microcks.quarkus:quarkus-microcks"
      - dependency-name: "io.quarkiverse.langchain4j:quarkus-langchain4j-bom"
      - dependency-name: "org.wiremock:wiremock-grpc-extension"

  # Dependencies for the rhbq-3.8 branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-3.8
    labels:
      - "version-upgrade"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      - dependency-name: "com.redhat.quarkus.platform:quarkus-bom"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "com.redhat.quarkus.platform:quarkus-maven-plugin"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "io.quarkus:quarkus-panache-common"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "io.github.microcks.quarkus:quarkus-microcks"
      - dependency-name: "io.quarkiverse.langchain4j:quarkus-langchain4j-bom"
      - dependency-name: "org.wiremock:wiremock-grpc-extension"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    labels:
      - "version-upgrade"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: 3.8.Final
    labels:
      - "version-upgrade"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-3.8
    labels:
      - "version-upgrade"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: 3.15.Final
    labels:
      - "version-upgrade"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-3.15
    labels:
      - "version-upgrade"
