
  fights-db:
    image: postgres:13
    container_name: fights-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../../rest-fights/deploy/db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ../../../rest-fights/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql
      - ../../../rest-fights/deploy/db-init/initialize-downstream-databases.sql:/docker-entrypoint-initdb.d/3-init-downstream-dbs.sql
      - ../../../rest-villains/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/4-init-villains-tables.sql
      - ../../../rest-heroes/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/5-init-heroes-tables.sql
    networks:
      default:
        aliases:
          - heroes-db
          - villains-db

  apicurio:
    image: apicurio/apicurio-registry-mem:2.1.5.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092
