
  rest-fights-native:
    image: quay.io/quarkus-super-heroes/rest-fights:native-latest
    container_name: rest-fights-native
    depends_on:
      - fights-db
      - apicurio
      - fights-kafka
    ports:
      - "8082:8082"
    environment:
      QUARKUS_MONGODB_HOSTS: fights-db:27017
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      QUARKUS_LIQUIBASE_MONGODB_MIGRATE_AT_START: "false"
      QUARKUS_MONGODB_CREDENTIALS_USERNAME: superfight
      QUARKUS_MONGODB_CREDENTIALS_PASSWORD: superfight
      QUARKUS_STORK__HERO_SERVICE__SERVICE_DISCOVERY_ADDRESS_LIST: rest-heroes:8083
      QUARKUS_STORK__VILLAIN_SERVICE__SERVICE_DISCOVERY_ADDRESS_LIST: rest-villains:8084
      QUARKUS_STORK__NARRATION_SERVICE__SERVICE_DISCOVERY_ADDRESS_LIST: rest-narration:8087
      QUARKUS_GRPC_CLIENTS_LOCATIONS_HOST: grpc-locations
      QUARKUS_GRPC_CLIENTS_LOCATIONS_PORT: 8089
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-fights
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
