paths:
  dockerfile:
    jvm-21: src/main/docker/Dockerfile.jvm21
  base-image:
    jvm-21: registry.access.redhat.com/ubi9/openjdk-21:1.17

quarkus:
  application:
    name: grpc-locations
  log:
    level: INFO
    category:
      "io.quarkus.sample.superheroes":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: INFO
      darken: 1
  http:
    port: 8089
    test-port: 0
  grpc:
    server:
      use-separate-server: false
      enable-reflection-service: true
      port: "${quarkus.http.port}"
      test-port: "${quarkus.http.test-port}"
  datasource:
    jdbc:
      telemetry: true
  otel:
    resource:
      attributes: "app=${quarkus.application.name},application=grpc-locations,system=quarkus-super-heroes"
    exporter:
      otlp:
        traces:
          endpoint: http://localhost:4317
  hibernate-orm:
    database:
      generation: drop-and-create
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"
  kubernetes:
    part-of: locations-service
    annotations:
      "app.openshift.io/connects-to": locations-db,otel-collector
    env:
      configmaps: "${quarkus.application.name}-config"
      secrets: "${quarkus.application.name}-config-creds"
    labels:
      app: "${quarkus.application.name}"
      application: "${quarkus.kubernetes.part-of}"
      system: quarkus-super-heroes
  openshift:
    base-jvm-image: registry.access.redhat.com/ubi9/openjdk-17:1.16
    base-native-image: quay.io/quarkus/ubi-quarkus-native-binary-s2i:2.0
    deployment-kind: deployment
    route:
      expose: true
      tls:
        termination: passthrough
        insecure-edge-termination-policy: None
    annotations:
      "app.openshift.io/connects-to": locations-db,otel-collector
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.kubernetes.part-of}"
      system: "${quarkus.kubernetes.labels.system}"
  knative:
    annotations:
      "app.openshift.io/connects-to": locations-db,otel-collector
      "serverless.openshift.io/default-enable-http2": 'true'
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.kubernetes.part-of}"
      system: "${quarkus.kubernetes.labels.system}"

"%dev,test":
  quarkus:
    log:
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        level: DEBUG

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql

"%kubernetes":
  quarkus:
    config:
      profile:
        parent: prod
    kubernetes:
      deployment-target: kubernetes

"%kubernetes-21":
  quarkus:
    config:
      profile:
        parent: kubernetes
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-21}"

"%openshift":
  quarkus:
    config:
      profile:
        parent: prod
    container-image:
      builder: openshift
    kubernetes:
      deployment-target: openshift

"%openshift-21":
  quarkus:
    config:
      profile:
        parent: openshift
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-21}"
    openshift:
      jvm-dockerfile: "${paths.dockerfile.jvm-21}"
      base-jvm-image: "${paths.base-image.jvm-21}"

"%knative":
  quarkus:
    config:
      profile:
        parent: prod
    kubernetes:
      deployment-target: knative

"%knative-21":
  quarkus:
    config:
      profile:
        parent: knative
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-21}"

"%knative-openshift":
  quarkus:
    config:
      profile:
        parent: knative
    container-image:
      builder: openshift

"%knative-openshift-21":
  quarkus:
    config:
      profile:
        parent: knative-openshift
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-21}"
    openshift:
      jvm-dockerfile: "${paths.dockerfile.jvm-21}"
      base-jvm-image: "${paths.base-image.jvm-21}"

"%minikube":
  quarkus:
    config:
      profile:
        parent: prod
    kubernetes:
      deployment-target: minikube

"%minikube-21":
  quarkus:
    config:
      profile:
        parent: minikube
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-21}"
