version: "3"
services:

  ui-super-heroes:
    image: quay.io/quarkus-super-heroes/ui-super-heroes:latest-rhbq-2.7
    container_name: ui-super-heroes
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      API_BASE_URL: http://localhost:8082
