
  rest-villains-native:
    image: quay.io/quarkus-super-heroes/rest-villains:native-latest
    container_name: rest-villains-native
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superbad
      QUARKUS_DATASOURCE_PASSWORD: superbad
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-villains
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
