
  rest-villains-native-java17:
    image: quay.io/quarkus-super-heroes/rest-villains:native-java17-latest
    container_name: rest-villains-native-java17
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-villains
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
