version: "3"
services:

  villains-db:
    image: postgres:14
    container_name: villains-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../../rest-villains/deploy/db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ../../../rest-villains/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql

  rest-villains-native-java17:
    image: quay.io/quarkus-super-heroes/rest-villains:native-java17-latest
    container_name: rest-villains-native-java17
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superbad
      QUARKUS_DATASOURCE_PASSWORD: superbad
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-villains
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
