
  ui-super-heroes-java21:
    image: quay.io/quarkus-super-heroes/ui-super-heroes:java21-latest-3.20.Final
    container_name: ui-super-heroes
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      API_BASE_URL: http://localhost:8082
