
  ui-super-heroes-java17:
    image: quay.io/quarkus-super-heroes/ui-super-heroes:java17-latest-rhbq-3.15
    container_name: ui-super-heroes
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      API_BASE_URL: http://localhost:8082
