version: "3"
services:

  fights-db:
    image: mongo:5.0
    container_name: fights-db
    ports:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ../../../rest-fights/deploy/db-init/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js

  apicurio:
    image: apicurio/apicurio-registry-mem:2.2.0.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092

  rest-fights-native-java11:
    image: quay.io/quarkus-super-heroes/rest-fights:native-java11-latest
    container_name: rest-fights-native-java11
    depends_on:
      - fights-db
      - apicurio
      - fights-kafka
      - rest-heroes-native-java11
      - rest-villains-native-java11
    ports:
      - "8082:8082"
    environment:
      QUARKUS_MONGODB_HOSTS: fights-db:27017
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      QUARKUS_LIQUIBASE_MONGODB_MIGRATE_AT_START: false
      QUARKUS_MONGODB_CREDENTIALS_USERNAME: superfight
      QUARKUS_MONGODB_CREDENTIALS_PASSWORD: superfight
      QUARKUS_REST_CLIENT_HERO_CLIENT_URL: http://rest-heroes:8083
      FIGHT_VILLAIN_CLIENT_BASE_URL: http://rest-villains:8084
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-fights
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
