---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app: apicurio
    application: fights-service
    system: quarkus-super-heroes
    app.openshift.io/runtime: apicurio
  name: apicurio
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apicurio
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: event-statistics
spec:
  lookupPolicy:
    local: false
  tags:
    - name: java11-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/event-statistics:java11-latest'
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: java17-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/event-statistics:java17-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
    - name: native-latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/quarkus-super-heroes/event-statistics:native-latest'
      importPolicy: { }
      referencePolicy:
        type: Source
