version: "3"
services:

  fights-db:
    image: mongo:5.0
    container_name: fights-db
    ports:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ../../rest-fights/deploy/db-init/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js

  apicurio:
    image: apicurio/apicurio-registry-mem:2.2.0.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092

  rest-fights-native-java17:
    image: quay.io/quarkus-super-heroes/rest-fights:native-java17-latest
    container_name: rest-fights-native-java17
    depends_on:
      - fights-db
      - apicurio
      - fights-kafka
      - rest-heroes-native-java17
      - rest-villains-native-java17
    ports:
      - "8082:8082"
    environment:
      QUARKUS_MONGODB_HOSTS: fights-db:27017
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      QUARKUS_LIQUIBASE_MONGODB_MIGRATE_AT_START: false
      QUARKUS_MONGODB_CREDENTIALS_USERNAME: superfight
      QUARKUS_MONGODB_CREDENTIALS_PASSWORD: superfight
      QUARKUS_REST_CLIENT_HERO_CLIENT_URL: http://rest-heroes:8083
      FIGHT_VILLAIN_CLIENT_BASE_URL: http://rest-villains:8084
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-fights
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

  villains-db:
    image: postgres:14
    container_name: villains-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superbad
      POSTGRES_PASSWORD: superbad
      POSTGRES_DB: villains_database
    volumes:
      - ../../rest-villains/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql

  heroes-db:
    image: postgres:14
    container_name: heroes-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ../../rest-heroes/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql

  rest-villains-native-java17:
    image: quay.io/quarkus-super-heroes/rest-villains:native-java17-latest
    container_name: rest-villains-native-java17
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superbad
      QUARKUS_DATASOURCE_PASSWORD: superbad
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-villains
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

  rest-heroes-native-java17:
    image: quay.io/quarkus-super-heroes/rest-heroes:native-java17-latest
    container_name: rest-heroes-native-java17
    depends_on:
      - heroes-db
    ports:
      - "8083:8083"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://heroes-db:5432/heroes_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superman
      QUARKUS_DATASOURCE_PASSWORD: superman
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-heroes
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

  event-statistics-native-java17:
    image: quay.io/quarkus-super-heroes/event-statistics:native-java17-latest
    container_name: event-statistics-native-java17
    depends_on:
      - apicurio
      - fights-kafka
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - event-statistics
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

  ui-super-heroes:
    image: quay.io/quarkus-super-heroes/ui-super-heroes:latest
    container_name: ui-super-heroes
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      API_BASE_URL: http://localhost:8082
