name: Create deploy resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

on:
  workflow_run:
    workflows:
      - "Build and Push Container images"
    branches:
      - main
      - rhbq-2.7
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}"
  cancel-in-progress: false

jobs:
  create-deploy-resources:
    if: ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && ((github.event.workflow_run.event == 'push') || (github.event.workflow_run.event == 'workflow_dispatch') || (github.event.workflow_run.event == 'workflow_run')) && (github.event.workflow_run.conclusion == 'success'))) && ((github.repository == 'quarkusio/quarkus-super-heroes') &&  ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/rhbq-2.7')))
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Create k8s resources
        shell: bash
        run: scripts/generate-k8s-resources.sh

      - name: Create docker-compose resources
        shell: bash
        run: scripts/generate-docker-compose-resources.sh

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate deploy resources (from ${{ github.workflow }} run # ${{ github.run_number }})"
          add: '["**/deploy/k8s/*.yml", "deploy/k8s/*.yml", "**/deploy/docker-compose/*.yml", "deploy/docker-compose/*.yml", "deploy/db-init/**"]'
          pathspec_error_handling: exitImmediately
