name: Dependabot auto-merge (rhbq-3.8)

on: 
  pull_request_target:
    branches:
      - main
      - 2.13.Final
      - 3.2.Final
      - 3.8.Final
      - rhbq-2.7
      - rhbq-2.13
      - rhbq-3.2
      - rhbq-3.8

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: (steps.metadata.outputs.update-type == 'version-update:semver-patch') || (steps.metadata.outputs.update-type == 'version-update:semver-minor')
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          echo "${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}" | gh auth login --with-token
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
