version: "3"
services:

  apicurio:
    image: apicurio/apicurio-registry-mem:2.1.5.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092

  event-statistics-native-java11:
    image: quay.io/quarkus-super-heroes/event-statistics:native-java11-latest
    container_name: event-statistics-native-java11
    depends_on:
      - apicurio
      - fights-kafka
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - event-statistics
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
